on: push
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - run: make message
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          ref: "hw-1"
      - name: Install cpplint
        run: pip install cpplint
      - name: Install libbsd-dev
        run: sudo apt-get install libbsd-dev
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: make check
        run: make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - name: install gtest
        run: sudo apt-get install googletest
      - name: Make build
        run: make build
