on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          ref: "hw-1"
      - name: Install cpplint
        run: pip install cpplint
      - name: Install libbsd-dev
        run: sudo apt-get install libbsd-dev
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: Make check
        run: make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - name: Install GTest
        run: |
          mkdir gtest 
          cd gtest
          git clone https://github.com/google/googletest.git 
          cd googletest 
          cmake -B build 
          cmake --build build 
          sudo cmake --install build
      - name: Install gcovr, lcov
        run: |
          sudo apt-get install gcovr
          sudo apt-get install lcov
      - name: Make build
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-test
          path: /home/runner/work/C_Cpp_HW/C_Cpp_HW/build
      - name: Make test
        run: make test
      - name: Make gcovr
        run: make gcovr
      - name: Make lcov
        run: make lcov
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: |
            /home/runner/work/C_Cpp_HW/C_Cpp_HW/build/view_composition/CMakeFiles/view_composition.dir/*.gcda
            /home/runner/work/C_Cpp_HW/C_Cpp_HW/build/view_composition/CMakeFiles/view_composition.dir/*.gcno
          # ./build/**/**/**/*.gcda
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install GTest
        run: |
          mkdir gtest 
          cd gtest
          git clone https://github.com/google/googletest.git 
          cd googletest 
          cmake -B build 
          cmake --build build 
          sudo cmake --install build
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: my-test
          path: /home/runner/work/C_Cpp_HW/C_Cpp_HW/build

      - name: Make test
        run: |
          sudo ./build/tests/test
      - name: Get gcovr
        run: make gcovr
      - name: Get lcov
        run: make lcov
