on: push
jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v1
  #       with:
  #         ref: "hw-1"
  #     - name: install cpplint
  #       run: pip install cpplint
  #     - name: install libbsd-dev
  #       run: sudo apt-get install libbsd-dev
  #     - name: install clang-tidy
  #       run: sudo apt-get install clang-tidy
  #     - name: install cppcheck
  #       run: sudo apt-get install cppcheck
  #     - name: make check
  #       run: make check
  build:
    runs-on: ubuntu-latest
    # needs: [check]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - name: install gtest
        run: |
          git clone https://github.com/google/googletest.git 
          cmake -B build
          cmake --build build
          cmake --install build
      - name: make build
        run: make build
