on: push
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - run: make message
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      # - name: install cpplint
      # run: 
      # - name: make check
      - run: |
        apt install cpplint
        make check