name: C/C++ CI configuration
on: push
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - run: make message
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cpplint
      run: apt install cpplint
      - name: make check
        with:
          ref: "hw-1"
      run: make check