on: push
jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v1
  #       with:
  #         ref: "hw-1"
  #     - name: Install cpplint
  #       run: pip install cpplint
  #     - name: Install libbsd-dev
  #       run: sudo apt-get install libbsd-dev
  #     - name: Install clang-tidy
  #       run: sudo apt-get install clang-tidy
  #     - name: Install cppcheck
  #       run: sudo apt-get install cppcheck
  #     - name: Make check
  #       run: make check
  build:
    runs-on: ubuntu-latest
    # needs: [check]
    # container: leshiy1295/gcc_linters
    steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-1"
      # - name: Install gtest
      #   uses: MarkusJx/googletest-installer@v1.1
      - run: cd /usr/lib && ls
      - run: sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make
      - run: cd /usr/src/gtest && ls
      - run: cd /usr/src/gtest/lib && ls
      - name: Configure gtest
        run: |
          sudo cp googletest/build/lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          sudo cp -R googletest/googletest/include/gtest /usr/include
      - name: make build
        run: make build
      # run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
