on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          ref: "hw-1"
      - name: Install cpplint
        run: pip install cpplint
      - name: Install libbsd-dev
        run: sudo apt-get install libbsd-dev
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: Make check
        run: make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    # container: leshiy1295/gcc_linters
    steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-1"
      # - name: Install gtest
      #   uses: MarkusJx/googletest-installer@v1.1
      - name: Install GTest
        run: mkdir gtest && cd gtest && git clone https://github.com/google/googletest.git && cd googletest && cmake -B build && cmake --build build && sudo cmake --install build
      - name: Install BSD support for Linux
        run: sudo apt-get install libbsd-dev
      # - name: Install GTest manually
      #   run: sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd /usr/src/gtest/lib && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Make build
        run: make build
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Make test
        run: make test
      - name: Get gcovr
        run: make gcovr
      - name: Get lcov
        run: make lcov
