on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - uses: actions/setup-python@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      # - name: Install clang-format
      #   run: sudo apt-get install clang-format
      - name: Make check
        run: make check
  build:
    runs-on: ubuntu-latest
    # needs: [check]
    steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-2"
      - name: Install GTest
        run: |
          cd gtest
          git clone https://github.com/google/googletest.git 
          cd googletest 
          cmake -B build 
          cmake --build build 
          sudo cmake --install build
      - name: Make build
        run: make build
      - name: Run valgrind
        run: valgrind build/main
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-2"
      - name: Install GTest
        run: |
          cd gtest
          git clone https://github.com/google/googletest.git 
          cd googletest 
          cmake -B build 
          cmake --build build 
          sudo cmake --install build
      - name: Make build
        run: make build
      - name: Make test
        run: make test
      - name: Make gcov
        run: |
          gcov -abcfu build/**/CMakeFiles/**/*.gcno
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          directory: |
            /home/runner/work/C_Cpp_HW/C_Cpp_HW/
          token: ${{ secrets.CODECOV_TOKEN }}
