on: push
jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v1
  #       with:
  #         ref: "hw-1"
  #     - name: install cpplint
  #       run: pip install cpplint
  #     - name: install libbsd-dev
  #       run: sudo apt-get install libbsd-dev
  #     - name: install clang-tidy
  #       run: sudo apt-get install clang-tidy
  #     - name: install cppcheck
  #       run: sudo apt-get install cppcheck
  #     - name: make check
  #       run: make check
  build:
    runs-on: ubuntu-latest
    # needs: [check]
    steps:
      - name: fetch
        uses: actions/checkout@v2
        with:
          ref: "hw-1"
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: make build
        run: make build
